export type Language = 'English' | 'Hindi' | 'Marathi';

export const TRANSLATIONS = {
  English: {
    title: "Aarogyam AI",
    subtitle: "Your Rural Health Assistant",
    symptomLabel: "Tell us how you're feeling...",
    symptomPlaceholder: "e.g., I have fever and headache since morning",
    voiceBtn: "Speak Your Symptoms",
    imageBtn: "Upload Skin Photo",
    analyzeBtn: "Check My Health",
    conditionsTitle: "Possible Conditions",
    reasoningTitle: "Why we think this",
    imageInsightTitle: "Image Insights",
    recommendationTitle: "What you should do",
    warningTitle: "Warning Signs",
    lowRisk: "Low Risk",
    mediumRisk: "Medium Risk",
    highRisk: "High Risk",
    startOver: "Start Over",
    loading: "Analyzing your health...",
    disclaimer: "Aarogyam is for guidance only. Not a medical diagnosis.",
    rest: "Rest & Hydration",
    doctor: "Visit a Doctor",
    urgent: "Urgent Care Needed",
    urgentWarning: "Seek help immediately if you have chest pain or difficulty breathing.",
    descriptionLabel: "Description",
    nextStepsLabel: "What you should do",
    speakResult: "Listen to Findings",
    stopSpeech: "Stop Listening",
    nearbyhospitals: "Nearby Hospitals",
    findingHospitals: "Finding nearby hospitals...",
    noHospitalsFound: "No hospitals found in this area.",
    hospitalInfo: "Recommended medical facilities near you:",
    getLocation: "Scan My Location (GPS)",
    locationDenied: "Location access denied. Use manual search below or enable GPS.",
    locationError: "Could not find your GPS location. Please use manual search.",
    quotaExceeded: "API Quota exceeded. Please try again in 1-2 minutes.",
    firstAidTitle: "First Aid Guides",
    historyTitle: "Past Assessments",
    noHistory: "No assessments yet.",
    emergencyTitle: "Emergency SOS",
    callAmbulance: "Call Ambulance (102)",
    callPolice: "Call Police (100)",
    infectionHubTitle: "Infection Watch",
    infectionCheckBtn: "Identify Specific Infection",
    commonInfections: {
        malaria: "Malaria (Fever with chills)",
        dengue: "Dengue (Severe pain behind eyes)",
        typhoid: "Typhoid (Step-ladder fever)",
        tb: "Tuberculosis (Cough > 2 weeks)"
    },
    guides: {
        fever: "Fever: Stay hydrated, use cold compress, rest.",
        wound: "Wounds: Clean with soap/water, apply pressure, keep covered.",
        snakebite: "Snakebite: Keep victim still, stay calm, DON'T suck venom, get to hospital.",
        burns: "Burns: Cool water for 10-20 min, no ice, no butter, cover loosely.",
        sunstroke: "Sunstroke: Move to shade, cool the body with water/fan, give sips of water.",
        dogbite: "Dog Bite: Wash with soap for 15 min, apply antiseptic, visit doctor for Rabies shot.",
        choking: "Choking: Stand behind, wrap arms around waist, perform 5 belly thrusts.",
        shock: "Electric Shock: DON'T touch directly, turn off power, check breathing, call 102."
    }
  },
  Hindi: {
    title: "आरोग्यम AI",
    subtitle: "आपका ग्रामीण स्वास्थ्य सहायक",
    symptomLabel: "बताएं कि आपको कैसा महसूस हो रहा है...",
    symptomPlaceholder: "जैसे: मुझे सुबह से बुखार और सिरदर्द है",
    voiceBtn: "बोलकर बताएं",
    imageBtn: "त्वचा की फोटो लें",
    analyzeBtn: "जांच करें",
    conditionsTitle: "संभावित स्थितियाँ",
    reasoningTitle: "निष्कर्ष का कारण",
    imageInsightTitle: "फोटो से जानकारी",
    recommendationTitle: "आपको क्या करना चाहिए",
    warningTitle: "खतरे के संकेत",
    lowRisk: "कम जोखिम",
    mediumRisk: "मध्यम जोखिम",
    highRisk: "उच्च जोखिम",
    startOver: "फिर से शुरू करें",
    loading: "स्वास्थ्य विश्लेषण हो रहा है...",
    disclaimer: "आरोग्यम केवल मार्गदर्शन के लिए है। यह चिकित्सा निदान नहीं है।",
    rest: "आराम और पानी पीना",
    doctor: "डॉक्टर के पास जाएं",
    urgent: "तत्काल सहायता की आवश्यकता",
    urgentWarning: "यदि सीने में दर्द या सांस लेने में कठिनाई हो तो तुरंत मदद लें।",
    descriptionLabel: "वृत्तांत (विवरण)",
    nextStepsLabel: "आपको क्या करना होगा",
    speakResult: "जांच सुनें",
    stopSpeech: "सुनना बंद करें",
    nearbyhospitals: "नजदीकी अस्पताल",
    findingHospitals: "नजदीकी अस्पतालों की खोज हो रही है...",
    noHospitalsFound: "इस क्षेत्र में कोई अस्पताल नहीं मिला।",
    hospitalInfo: "आपके पास अनुशंसित चिकित्सा सुविधाएं:",
    getLocation: "लोकेशन स्कैन करें (GPS)",
    locationDenied: "लोकेशन एक्सेस नहीं मिला। नीचे मॅन्युअल सर्च करें या GPS चालू करें।",
    locationError: "आपकी लोकेशन नहीं मिली। कृपया मॅन्युअल सर्च का उपयोग करें।",
    quotaExceeded: "API कोटा समाप्त हो गया है। कृपया 1-2 मिनट में पुनः प्रयास करें।",
    firstAidTitle: "प्राथमिक चिकित्सा गाइड",
    historyTitle: "पिछली जांच",
    noHistory: "अभी तक कोई जांच नहीं हुई।",
    emergencyTitle: "आपातकालीन SOS",
    callAmbulance: "एम्बुलेंस (102)",
    callPolice: "पुलिस (100)",
    infectionHubTitle: "संक्रमण वॉच",
    infectionCheckBtn: "विशिष्ट संक्रमण की पहचान करें",
    commonInfections: {
        malaria: "मलेरिया (ठंड के साथ बुखार)",
        dengue: "डेंगू (आंखों के पीछे तेज दर्द)",
        typhoid: "टाइफाइड (लगातार बढ़ता बुखार)",
        tb: "टीबी (2 सप्ताह से अधिक खांसी)"
    },
    guides: {
        fever: "बुखार: भरपूर पानी पिएं, ठंडी पट्टी लगाएं, आराम करें।",
        wound: "घाव: साबुन/पानी से धोएं, दबाव डालें, पट्टी बांधें।",
        snakebite: "सर्पदंश: मरीज को स्थिर रखें, शांत रहें, जहर चूसने की कोशिश न करें, तुरंत अस्पताल ले जाएं।",
        burns: "जलन: 10-20 मिनट ठंडा पानी डालें, बर्फ न लगाएं, मक्खन न लगाएं, हल्के से ढकें।",
        sunstroke: "लू लगना (Sunstroke): छाया में ले जाएं, शरीर को ठंडा करें, धीरे-धीरे पानी पिलाएं।",
        dogbite: "कुत्ते का काटना: 15 मिनट साबुन से धोएं, एंटीसेप्टिक लगाएं, रेबीज इंजेक्शन के लिए जाएं।",
        choking: "दम घुटना: पीड़ित के पीछे खड़े हों, कमर के चारों ओर हाथ लपेटें, 5 बार पेट दबाएं।",
        shock: "इलेक्ट्रिक शॉक: सीधे न छुएं, बिजली बंद करें, श्वास जांचें, 102 पर कॉल करें।"
    }
  },
  Marathi: {
    title: "आरोग्यम AI",
    subtitle: "तुमचा ग्रामीण आरोग्य सहाय्यक",
    symptomLabel: "तुम्हाला कसे वाटत आहे ते सांगा...",
    symptomPlaceholder: "उदा: मला सकाळपासून ताप आणि डोकेदुखी आहे",
    voiceBtn: "बोलून सांगा",
    imageBtn: "त्वचेचा फोटो घ्या",
    analyzeBtn: "आरोग्य तपासा",
    conditionsTitle: "संभावित आजार",
    reasoningTitle: "निष्कर्ष काढण्याचे कारण",
    imageInsightTitle: "फोटोतून माहिती",
    recommendationTitle: "तुम्ही काय करावे",
    warningTitle: "धोक्याचे संकेत",
    lowRisk: "कमी धोका",
    mediumRisk: "मध्यम धोका",
    highRisk: "जास्त धोका",
    startOver: "पुन्हा सुरू करा",
    loading: "आरोग्य विश्लेषण चालू आहे...",
    disclaimer: "आरोग्यम केवळ मार्गदर्शनासाठी आहे। हे वैद्यकीय निदान नाही।",
    rest: "आराम आणि पाणी पिणे",
    doctor: "डॉक्टरकडे जा",
    urgent: "तातडीच्या मदतीची गरज",
    urgentWarning: "छातीत दुखत असल्यास किंवा श्वास घेण्यास त्रास होत असल्यास त्वरित मदत घ्या।",
    descriptionLabel: "वृत्तांत (वर्णन)",
    nextStepsLabel: "तुम्हाला काय करावे लागेल",
    speakResult: "तपासणी ऐका",
    stopSpeech: "ऐकणे थांबवा",
    nearbyhospitals: "जवळची रुग्णालये",
    findingHospitals: "नजदीकी रुग्णालयांचा शोध सुरू आहे...",
    noHospitalsFound: "या भागात कोणतीही रुग्णालये आढळली नाहीत.",
    hospitalInfo: "तुमच्याजवळील शिफारस केलेल्या वैद्यकीय सुविधा:",
    getLocation: "लोकेशन स्कॅन करा (GPS)",
    locationDenied: "लोकेशन एक्सेस नाकारला. खाली मॅन्युअली शोधा किंवा GPS सक्षम करा.",
    locationError: "तुमची लोकेशन सापडली नाही. कृपया मॅन्युअली शोधा.",
    quotaExceeded: "API कोटा संपला आहे. कृपया 1-2 मिनिटात पुन्हा प्रयत्न करा।",
    firstAidTitle: "प्रथमोपचार मार्गदर्शक",
    historyTitle: "मागील तपासणी",
    noHistory: "अजून कोणतीही तपासणी झालेली नाही।",
    emergencyTitle: "आणीबाणी SOS",
    callAmbulance: "रुग्णवाहिका (102)",
    callPolice: "पोलीस (100)",
    infectionHubTitle: "संसर्ग वॉच",
    infectionCheckBtn: "विशिष्ट संसर्ग ओळखा",
    commonInfections: {
        malaria: "मलेरिया (थंडी वाजून ताप)",
        dengue: "डेंग्यू (डोळ्यांच्या मागे तीव्र वेदना)",
        typhoid: " टायफॉइड (सतत वाढणारा ताप)",
        tb: "टीबी (२ आठवड्यांहून अधिक खोकला)"
    },
    guides: {
        fever: "ताप: भरपूर पाणी प्या, थंड पट्टी लावा, आराम करा।",
        wound: "जखम: साबण/पाण्याने स्वच्छ करा, दाब द्या, झाकून ठेवा।",
        snakebite: "सर्पदंश: रुग्णाला स्थिर ठेवा, शांत राहा, विष ओढण्याचा प्रयत्न करू नका, लगेच रुग्णालयात न्या।",
        burns: "भाजणे: 10-20 मिनिटे थंड पाणी टाका, बर्फ लावू नका, लोणी लावू नका, हलके झाका।",
        sunstroke: "उष्माघात: सावलीत न्या, शरीर थंड करा, थोडे थोडे पाणी प्यायला द्या।",
        dogbite: "कुत्र्याचे चावणे: १५ मिनिटे साबणाने धुवा, अँटीसेप्टिक लावा, डॉक्टरांकडे जा।",
        choking: "गुदमरणे: पाठीमागे उभे राहा, कंबरेभोवती हात गुंडाळा आणि ५ वेळा पोट दाबा।",
        shock: "इलेक्ट्रिक शॉक: थेट स्पर्श करू नका, वीज बंद करा, श्वास तपासा, १०२ ला कॉल करा।"
    }
  }
};
